spring.application.name=api-gateway
server.port=8080

# Gateway Routes
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=delivery-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DELIVERY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/deliveries/**

spring.cloud.gateway.server.webflux.routes[2].id=tracking-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://TRACKING-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/tracking/**

spring.cloud.gateway.server.webflux.routes[3].id=admin-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/admin/**

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedOrigins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedHeaders=*

# Swagger aggregation
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Delivery Service
springdoc.swagger-ui.urls[1].url=/deliveries/v3/api-docs

springdoc.swagger-ui.urls[2].name=Tracking Service
springdoc.swagger-ui.urls[2].url=/tracking/v3/api-docs

springdoc.swagger-ui.urls[3].name=Admin Service
springdoc.swagger-ui.urls[3].url=/admin/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html

# Reactive app
spring.main.web-application-type=reactive
