# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Eureka
eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=*
