spring.application.name=tracking-service
server.port=8080

# PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://postgres:5432/tracking_db2
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.com.capg.tracking=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/tracking/v3/api-docs
server.forward-headers-strategy=framework

# RabbitMQ (Docker)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# File Upload Limits
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
